/**
 * @file WorkoutPlan.tsx
 * @copyright Copyright (c) 2024 Aryan Acharya
 * @license MIT
 */

import React from 'react';
import { motion } from 'framer-motion';
import { Clock, Activity, AlertCircle } from 'lucide-react';

interface WorkoutPlanProps {
  plan: string;
}

export function WorkoutPlan({ plan }: WorkoutPlanProps) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="bg-white rounded-lg shadow-lg p-6 max-w-2xl w-full"
    >
      <div className="prose max-w-none">
        <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
          <Activity className="w-6 h-6 text-blue-600" />
          Your Personalized Workout Plan
        </h2>
        
        <div className="flex items-center gap-2 text-gray-600 mb-4">
          <Clock className="w-5 h-5" />
          <span>Generated just now</span>
        </div>

        <div className="bg-blue-50 border-l-4 border-blue-500 p-4 mb-6">
          <div className="flex items-start gap-2">
            <AlertCircle className="w-5 h-5 text-blue-600 mt-0.5" />
            <p className="text-sm text-blue-700">
              Always warm up before starting your workout and listen to your body. 
              If you experience pain, stop and consult a healthcare professional.
            </p>
          </div>
        </div>

        <div className="whitespace-pre-wrap font-mono text-sm">
          {plan}
        </div>

        <div className="mt-6 pt-4 border-t text-xs text-gray-500 text-right">
          Generated by AI Workout Planner | © 2025 Aryan Acharya
        </div>
      </div>
    </motion.div>
  );
}